# -------------------------------------------------------
# Main settings for the WPMoo project.
# -------------------------------------------------------

# Core project metadata.
project:
  name: "PROJECT_NAME"
  namespace: "PROJECT_NAMESPACE"
  text_domain: "PROJECT_TEXT_DOMAIN"

# Global theme setting.
theme: "amber"

# Development environment specific settings.
dev:
  browser_sync:
    enabled: true
    url: "http://localhost" # dynamic URL based on project slug
    port: 3000
    open: true
    notify: false
    files:
      - "./**/*.php"
      - "./assets/js/**/*.js"
      - "./assets/css/**/*.css"
