# Core project metadata.
project:
  name: "PROJECT_NAME"
  namespace: "PROJECT_NAMESPACE"
  text_domain: "PROJECT_TEXT_DOMAIN"

localization:
  translator: "PROJECT_AUTHOR_NAME <PROJECT_AUTHOR_EMAIL>"
  bug_reports: "https://github.com/wpmoo-org/wpmoo/issues"
  copyright_text: |
    # Copyright (C) 2025 WPMoo.org
    # This file is distributed under the GPL-2.0+.

# Development environment specific settings.
dev:
  browser_sync:
    enabled: false
    url: "https://localhost" # dynamic URL based on project slug
    port: 3000
    open: true
    notify: false
    files:
      - "./**/*.php"
      - "./assets/js/**/*.js"
      - "./assets/css/**/*.css"
  theme: "amber"
